### ISSUE TITLE
Unsupported MIME type

### ISSUE THREAD

**Issue by slidenerd** [alamcordeiro/qrnode#1]
I was trying to decode [this ](https://lh4.ggpht.com/bQb_EhhqNvG6zlSOhI5vr6rXnZQERBFzGI-KrEGSOnCBHU1yainkA-46Yjq2dEBwIRI=w300)QR code on the browser

Error: Unsupported MIME type: application/octet-stream
    at Jimp.parseBitmap (D:\bots\qrbot\node_modules\jimp\jimp.js:108:19)
    at new Jimp (D:\bots\qrbot\node_modules\jimp\jimp.js:70:21)
    at Request._callback (D:\bots\qrbot\node_modules\qrnode\index.js:11:17)
    at Request.self.callback (D:\bots\qrbot\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (D:\bots\qrbot\node_modules\request\request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (D:\bots\qrbot\node_modules\request\request.js:1001:12)

Any ideas what might be the cause? Thanks for the awesome library and your answers in advance

**Comment by ocordeiro** [comment]
Please, check if last update solve it
